version: '3.9'
services:
  php:
      # image: php:7.0.33-fpm-jessie
      build:
        context: .
        dockerfile: ./Dockerfile
      depends_on: 
        - db
      working_dir: /var/www/html
      # restart: always
      volumes:
          - ./:/var/www/html
          # - ./apache:/etc/apache2/sites-available/
      
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb
    restart: always
    volumes:
      - ./data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]